import { MantineProvider, Button } from '@mantine/core';
import { Head } from 'next/document';
import { Component } from 'react';

function App() {
  return <Button>My app button</Button>;
}

// Custom theme is applied to all components in App
function PREPLAND() {
  return (
    <>
      <Head>
        <title>PREPLAND</title>
        <meta 
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/alphabet-a.ico" />
      </Head>

      <MantineProvider theme={{ fontFamily: 'Open Sans' }} withGlobalStyles withNormalizeCSS>
        <Component {...pageProps} />
      </MantineProvider>
    </>
  );
}

export default PREPLAND;