import "@fontsource/poppins/300.css";
import "@fontsource/poppins/400.css";
import "@fontsource/poppins/500.css";
import "@fontsource/poppins/600.css";
import "@fontsource/poppins/700.css";
import "@fontsource/poppins/800.css";
import "@fontsource/poppins/900.css";
import { MantineProvider, Button, Header } from '@mantine/core';
import { Head } from 'next/document';
import { Component } from 'react';

function App() {
  return <Button>My app button</Button>;
}

// Custom theme is applied to all components in App
function PREPLAND(props) {
  const { Component, pageProps } = props;

  return (
    <>
      <Head>
        <title>PREPLAND</title>
        <meta 
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/alphabet-a.ico" />
      </Head>

      <MantineProvider 
        withGlobalStyles 
        withNormalizeCSS
        theme={{ 
          fontFamily: 'Poppins, sans-serif'
        }} 
      >
          <Component {...pageProps} />
      </MantineProvider>
    </>
  );
}

export default PREPLAND;